export const skills: string[] = [
  'Java (Backend)',
  'Python (Backend)',
  'JavaScript (Frontend)',
  'React (Frontend)',
  'Angular (Frontend)',
  'Node.js (Backend)',
  'C++ (Backend)',
  'HTML5 and CSS3 (Frontend)',
  'SQL (Relational Database)',
  'MongoDB (NoSQL Database)',
  'Object-Oriented Development (OOD)',
  'Agile Methodologies (Scrum, Kanban)',
  'Git (Version Control)',
  'Jenkins (CI/CD)',
  'Selenium (Automated Testing)',
  'Security in Software Development',
  'Docker (Containerization)',
  'Kubernetes (Container Orchestration)',
  'AWS (Amazon Web Services)',
  'Azure (Microsoft Cloud)',
  'Google Cloud Platform (GCP)',
  'Ansible (Automation)',
  'Networking and Operating Systems',
  'TensorFlow (Machine Learning)',
  'PyTorch (Machine Learning)',
  'Data Analysis and Data Science',
  'Understanding Software Development Life Cycle',
  'Complex Problem Solving',
  'Teamwork and Collaboration',
  'Jira (Project Management)',
  'Trello (Project Management)',
  'Proactive Attitude for Continuous Learning',
  'Adaptability to Rapid Changes',
  'Analytical and Critical Thinking',
  'Clear and Comprehensive Documentation',
  'Interpretation and Fulfillment of Customer Requirements',
  'Algorithmic Problem-Solving Ability',
  'Effective Technical Communication',
  'Ethics and Security Awareness',
  'Optimization of Application and System Performance'
]
